global using Classificador.Api.Domain;
global using Classificador.Api.Domain.Entities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Classificador.Api.Infrastructure.Context.Configurations;
global using Classificador.Api.Infrastructure.Context;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Classificador.Api.Domain.Interfaces.Repositories;
