global using System;
global using Classificador.Api.Domain.Enums; 
global using Classificador.Api.Domain.Interfaces;
global using Classificador.Api.SharedKernel.Shared;
global using Classificador.Api.Domain.Entities;
global using System.Security.Claims;
global using Classificador.Api.Domain.Models;
global using Classificador.Api.SharedKernel.Shared.Errors;
global using Classificador.Api.Domain.ValueObjects.NamedEntity;
